predicting turbine energy yield (TEY) using ambient variables as features.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
import tensorflow as tf
from tensorflow.keras import layers, models

In [2]:
df = pd.read_csv('gas_turbines.csv')

In [3]:
df

,AT,AP,AH,AFDP,GTEP,TIT,TAT,TEY,CDP,CO,NOX
0,6.8594,1007.9,96.799,3.5000,19.663,1059.2,550.00,114.70,10.605,3.1547,82.722
1,6.7850,1008.4,97.118,3.4998,19.728,1059.3,550.00,114.72,10.598,3.2363,82.776
2,6.8977,1008.8,95.939,3.4824,19.779,1059.4,549.87,114.71,10.601,3.2012,82.468
3,7.0569,1009.2,95.249,3.4805,19.792,1059.6,549.99,114.72,10.606,3.1923,82.670
4,7.3978,1009.7,95.150,3.4976,19.765,1059.7,549.98,114.72,10.612,3.2484,82.311
...,...,...,...,...,...,...,...,...,...,...,...
15034,9.0301,1005.6,98.460,3.5421,19.164,1049.7,546.21,111.61,10.400,4.5186,79.559
15035,7.8879,1005.9,99.093,3.5059,19.414,1046.3,543.22,111.78,10.433,4.8470,79.917
15036,7.2647,1006.3,99.496,3.4770,19.530,1037.7,537.32,110.19,10.483,7.9632,90.912
15037,7.0060,1006.8,99.008,3.4486,19.377,1043.2,541.24,110.74,10.533,6.2494,93.227
15038,6.9279,1007.2,97.533,3.4275,19.306,1049.9,545.85,111.58,10.583,4.9816,92.498

In [4]:
df.isna().sum()

AT      0
AP      0
AH      0
AFDP    0
GTEP    0
TIT     0
TAT     0
TEY     0
CDP     0
CO      0
NOX     0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15039 entries, 0 to 15038
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AT      15039 non-null  float64
 1   AP      15039 non-null  float64
 2   AH      15039 non-null  float64
 3   AFDP    15039 non-null  float64
 4   GTEP    15039 non-null  float64
 5   TIT     15039 non-null  float64
 6   TAT     15039 non-null  float64
 7   TEY     15039 non-null  float64
 8   CDP     15039 non-null  float64
 9   CO      15039 non-null  float64
 10  NOX     15039 non-null  float64
dtypes: float64(11)
memory usage: 1.3 MB

In [6]:
X = df.drop('TEY', axis=1)
y = df['TEY']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [8]:
X_train

,AT,AP,AH,AFDP,GTEP,TIT,TAT,CDP,CO,NOX
10187,17.4200,1015.4,56.526,3.5327,24.659,1087.8,550.05,11.979,1.52160,73.865
581,10.3210,1029.1,84.519,5.7759,33.104,1100.2,528.33,14.082,1.93590,71.891
1090,8.9166,1017.7,94.937,6.2532,33.701,1099.9,527.26,14.081,0.58865,78.189
6753,14.3080,1020.8,86.602,2.2080,18.882,1053.2,548.95,10.472,4.96240,67.287
1467,17.6370,1004.7,61.288,4.9691,25.059,1087.9,549.88,11.957,1.05220,76.902
...,...,...,...,...,...,...,...,...,...,...
13123,23.1770,1017.4,73.491,3.2509,20.246,1061.2,549.96,10.831,2.67630,57.271
3264,29.7670,1012.5,66.533,4.2209,26.290,1093.9,549.98,12.222,1.77170,64.133
9845,12.4800,1016.7,72.020,4.1439,29.251,1099.8,537.65,13.503,0.88512,65.532
10799,26.2940,1011.1,65.623,3.5515,23.846,1080.9,550.27,11.598,1.10500,60.692
2732,18.5570,1012.4,92.269,3.5571,19.429,1055.0,549.96,10.390,4.24680,60.571

In [9]:
X_test

,AT,AP,AH,AFDP,GTEP,TIT,TAT,CDP,CO,NOX
7052,15.3040,1000.3,65.933,3.0021,24.361,1085.2,549.86,11.896,1.27910,77.036
13849,16.3320,1020.6,57.919,4.9235,31.802,1100.0,531.67,13.820,1.15540,70.765
13112,27.6380,1017.0,57.860,4.1522,25.954,1094.5,550.37,12.241,1.11050,65.651
5268,23.7750,1009.3,86.774,4.3658,25.787,1092.0,550.04,12.181,1.79170,63.681
8720,7.6426,1013.2,82.689,4.0112,23.502,1083.7,550.12,11.731,1.56420,82.617
...,...,...,...,...,...,...,...,...,...,...
9973,13.4160,1010.1,100.130,3.2325,19.625,1054.1,547.37,10.601,4.76850,77.677
3539,27.5860,1009.3,77.724,4.1525,26.033,1092.3,550.45,12.048,1.59880,57.541
2180,17.3370,1003.6,82.099,5.0158,24.913,1086.1,550.14,11.825,0.67895,65.615
9596,13.6830,1014.7,86.376,4.4516,24.383,1087.2,549.41,12.011,1.48860,72.297
5218,23.6510,1011.0,71.111,4.2408,25.605,1090.4,549.93,12.089,1.87300,65.055

In [10]:
y_train

10187    133.66
581      160.99
1090     162.69
6753     110.01
1467     133.70
          ...
13123    112.04
3264     133.80
9845     155.46
10799    126.28
2732     109.74
Name: TEY, Length: 12031, dtype: float64

In [11]:
y_test

7052     134.06
13849    155.98
13112    133.77
5268     134.02
8720     134.14
          ...
9973     112.56
3539     133.74
2180     133.23
9596     134.71
5218     133.76
Name: TEY, Length: 3008, dtype: float64

In [12]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
model = models.Sequential()
model.add(layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(1))

In [14]:
model.compile(optimizer='adam', loss='mse', metrics=['mae', 'mape'])

In [15]:
history = model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/50
376/376 [==============================] - 5s 7ms/step - loss: 5284.0952 - mae: 54.9998 - mape: 41.0220 - val_loss: 353.4607 - val_mae: 14.8534 - val_mape: 11.1214
Epoch 2/50
376/376 [==============================] - 2s 5ms/step - loss: 226.8855 - mae: 11.4615 - mape: 8.5717 - val_loss: 144.6995 - val_mae: 8.8851 - val_mape: 6.6562
Epoch 3/50
376/376 [==============================] - 2s 5ms/step - loss: 112.0167 - mae: 7.6435 - mape: 5.7477 - val_loss: 89.2048 - val_mae: 6.6801 - val_mape: 5.0750
Epoch 4/50
376/376 [==============================] - 2s 5ms/step - loss: 71.4123 - mae: 5.9046 - mape: 4.4705 - val_loss: 59.3439 - val_mae: 5.2425 - val_mape: 3.9933
Epoch 5/50
376/376 [==============================] - 2s 5ms/step - loss: 47.2426 - mae: 4.6867 - mape: 3.5611 - val_loss: 41.1430 - val_mae: 4.2372 - val_mape: 3.2399
Epoch 6/50
376/376 [==============================] - 2s 5ms/step - loss: 31.6157 - mae: 3.7264 - mape: 2.8376 - val_loss: 26.6016 - val_mae: 3.3473 - val_mape: 2.5653
Epoch 7/50
376/376 [==============================] - 2s 5ms/step - loss: 20.6577 - mae: 2.9945 - mape: 2.2826 - val_loss: 17.3652 - val_mae: 2.6731 - val_mape: 2.0523
Epoch 8/50
376/376 [==============================] - 2s 5ms/step - loss: 12.9215 - mae: 2.3434 - mape: 1.7903 - val_loss: 11.5755 - val_mae: 2.1145 - val_mape: 1.6340
Epoch 9/50
376/376 [==============================] - 2s 5ms/step - loss: 8.0355 - mae: 1.8353 - mape: 1.4022 - val_loss: 6.9071 - val_mae: 1.6322 - val_mape: 1.2536
Epoch 10/50
376/376 [==============================] - 2s 5ms/step - loss: 4.8393 - mae: 1.4080 - mape: 1.0716 - val_loss: 4.4855 - val_mae: 1.3080 - val_mape: 1.0018
Epoch 11/50
376/376 [==============================] - 2s 5ms/step - loss: 3.0633 - mae: 1.1247 - mape: 0.8539 - val_loss: 2.8461 - val_mae: 1.0465 - val_mape: 0.7976
Epoch 12/50
376/376 [==============================] - 2s 6ms/step - loss: 2.0535 - mae: 0.9329 - mape: 0.7054 - val_loss: 2.1442 - val_mae: 0.8988 - val_mape: 0.6855
Epoch 13/50
376/376 [==============================] - 2s 6ms/step - loss: 1.4779 - mae: 0.8073 - mape: 0.6079 - val_loss: 1.5172 - val_mae: 0.7566 - val_mape: 0.5732
Epoch 14/50
376/376 [==============================] - 2s 6ms/step - loss: 1.0313 - mae: 0.6947 - mape: 0.5213 - val_loss: 1.2802 - val_mae: 0.7058 - val_mape: 0.5329
Epoch 15/50
376/376 [==============================] - 2s 5ms/step - loss: 0.8637 - mae: 0.6385 - mape: 0.4793 - val_loss: 1.3090 - val_mae: 0.6923 - val_mape: 0.5343
Epoch 16/50
376/376 [==============================] - 2s 5ms/step - loss: 0.6838 - mae: 0.5912 - mape: 0.4429 - val_loss: 0.6722 - val_mae: 0.5569 - val_mape: 0.4168
Epoch 17/50
376/376 [==============================] - 2s 5ms/step - loss: 0.5959 - mae: 0.5569 - mape: 0.4159 - val_loss: 0.6260 - val_mae: 0.5280 - val_mape: 0.3985
Epoch 18/50
376/376 [==============================] - 2s 5ms/step - loss: 0.5607 - mae: 0.5404 - mape: 0.4033 - val_loss: 0.5694 - val_mae: 0.5242 - val_mape: 0.3946
Epoch 19/50
376/376 [==============================] - 2s 5ms/step - loss: 0.5156 - mae: 0.5259 - mape: 0.3907 - val_loss: 0.4834 - val_mae: 0.4915 - val_mape: 0.3671
Epoch 20/50
376/376 [==============================] - 2s 5ms/step - loss: 0.5262 - mae: 0.5379 - mape: 0.4019 - val_loss: 0.4626 - val_mae: 0.4862 - val_mape: 0.3648
Epoch 21/50
376/376 [==============================] - 2s 6ms/step - loss: 0.4605 - mae: 0.5009 - mape: 0.3725 - val_loss: 0.4715 - val_mae: 0.4977 - val_mape: 0.3712
Epoch 22/50
376/376 [==============================] - 2s 5ms/step - loss: 0.4986 - mae: 0.5197 - mape: 0.3880 - val_loss: 0.4023 - val_mae: 0.4534 - val_mape: 0.3389
Epoch 23/50
376/376 [==============================] - 2s 5ms/step - loss: 0.4986 - mae: 0.5228 - mape: 0.3900 - val_loss: 0.6773 - val_mae: 0.6197 - val_mape: 0.4769
Epoch 24/50
376/376 [==============================] - 2s 5ms/step - loss: 0.5866 - mae: 0.5672 - mape: 0.4242 - val_loss: 0.4509 - val_mae: 0.4860 - val_mape: 0.3646
Epoch 25/50
376/376 [==============================] - 2s 5ms/step - loss: 0.4356 - mae: 0.4894 - mape: 0.3649 - val_loss: 0.6276 - val_mae: 0.5544 - val_mape: 0.4123
Epoch 26/50
376/376 [==============================] - 2s 5ms/step - loss: 0.4672 - mae: 0.5059 - mape: 0.3773 - val_loss: 0.4561 - val_mae: 0.5012 - val_mape: 0.3760
Epoch 27/50
376/376 [==============================] - 2s 5ms/step - loss: 0.4519 - mae: 0.4986 - mape: 0.3715 - val_loss: 0.5331 - val_mae: 0.5714 - val_mape: 0.4357
Epoch 28/50
376/376 [==============================] - 2s 5ms/step - loss: 0.4222 - mae: 0.4845 - mape: 0.3608 - val_loss: 0.4582 - val_mae: 0.4937 - val_mape: 0.3722
Epoch 29/50
376/376 [==============================] - 2s 5ms/step - loss: 0.5999 - mae: 0.5622 - mape: 0.4215 - val_loss: 0.3700 - val_mae: 0.4336 - val_mape: 0.3230
Epoch 30/50
376/376 [==============================] - 2s 5ms/step - loss: 0.4339 - mae: 0.4922 - mape: 0.3659 - val_loss: 0.3900 - val_mae: 0.4569 - val_mape: 0.3422
Epoch 31/50
376/376 [==============================] - 2s 5ms/step - loss: 0.4534 - mae: 0.4990 - mape: 0.3717 - val_loss: 0.4174 - val_mae: 0.4788 - val_mape: 0.3544
Epoch 32/50
376/376 [==============================] - 2s 5ms/step - loss: 0.4699 - mae: 0.5136 - mape: 0.3842 - val_loss: 0.4204 - val_mae: 0.4672 - val_mape: 0.3483
Epoch 33/50
376/376 [==============================] - 2s 5ms/step - loss: 0.4207 - mae: 0.4810 - mape: 0.3589 - val_loss: 0.5374 - val_mae: 0.5439 - val_mape: 0.4078
Epoch 34/50
376/376 [==============================] - 2s 6ms/step - loss: 0.4184 - mae: 0.4798 - mape: 0.3568 - val_loss: 0.4565 - val_mae: 0.4815 - val_mape: 0.3672
Epoch 35/50
376/376 [==============================] - 2s 5ms/step - loss: 0.4397 - mae: 0.4949 - mape: 0.3688 - val_loss: 0.3494 - val_mae: 0.4230 - val_mape: 0.3140
Epoch 36/50
376/376 [==============================] - 2s 5ms/step - loss: 0.4387 - mae: 0.4922 - mape: 0.3666 - val_loss: 0.4145 - val_mae: 0.4563 - val_mape: 0.3422
Epoch 37/50
376/376 [==============================] - 2s 5ms/step - loss: 0.4159 - mae: 0.4794 - mape: 0.3580 - val_loss: 0.5091 - val_mae: 0.5253 - val_mape: 0.3865
Epoch 38/50
376/376 [==============================] - 2s 5ms/step - loss: 0.4361 - mae: 0.4960 - mape: 0.3712 - val_loss: 0.4402 - val_mae: 0.4633 - val_mape: 0.3464
Epoch 39/50
376/376 [==============================] - 2s 5ms/step - loss: 0.4435 - mae: 0.4920 - mape: 0.3675 - val_loss: 1.2815 - val_mae: 0.7557 - val_mape: 0.5867
Epoch 40/50
376/376 [==============================] - 2s 6ms/step - loss: 0.4343 - mae: 0.4914 - mape: 0.3671 - val_loss: 1.3347 - val_mae: 0.8128 - val_mape: 0.6492
Epoch 41/50
376/376 [==============================] - 2s 5ms/step - loss: 0.5438 - mae: 0.5443 - mape: 0.4090 - val_loss: 0.4435 - val_mae: 0.4723 - val_mape: 0.3503
Epoch 42/50
376/376 [==============================] - 2s 5ms/step - loss: 0.4834 - mae: 0.5136 - mape: 0.3843 - val_loss: 0.5269 - val_mae: 0.5571 - val_mape: 0.4200
Epoch 43/50
376/376 [==============================] - 2s 5ms/step - loss: 0.4116 - mae: 0.4812 - mape: 0.3597 - val_loss: 0.3847 - val_mae: 0.4389 - val_mape: 0.3292
Epoch 44/50
376/376 [==============================] - 2s 5ms/step - loss: 0.4224 - mae: 0.4810 - mape: 0.3594 - val_loss: 0.6389 - val_mae: 0.6084 - val_mape: 0.4379
Epoch 45/50
376/376 [==============================] - 2s 5ms/step - loss: 0.4422 - mae: 0.4970 - mape: 0.3715 - val_loss: 0.3176 - val_mae: 0.4018 - val_mape: 0.2980
Epoch 46/50
376/376 [==============================] - 2s 5ms/step - loss: 0.4155 - mae: 0.4788 - mape: 0.3575 - val_loss: 0.3573 - val_mae: 0.4323 - val_mape: 0.3235
Epoch 47/50
376/376 [==============================] - 2s 5ms/step - loss: 0.3958 - mae: 0.4666 - mape: 0.3474 - val_loss: 0.5600 - val_mae: 0.6024 - val_mape: 0.4538
Epoch 48/50
376/376 [==============================] - 2s 5ms/step - loss: 0.4027 - mae: 0.4695 - mape: 0.3506 - val_loss: 0.9578 - val_mae: 0.7329 - val_mape: 0.5432
Epoch 49/50
376/376 [==============================] - 2s 6ms/step - loss: 0.4342 - mae: 0.4886 - mape: 0.3647 - val_loss: 0.3605 - val_mae: 0.4310 - val_mape: 0.3207
Epoch 50/50
376/376 [==============================] - 2s 5ms/step - loss: 0.4254 - mae: 0.4855 - mape: 0.3637 - val_loss: 0.4481 - val_mae: 0.4969 - val_mape: 0.3765

In [16]:
test_loss, test_mae, test_mape = model.evaluate(X_test, y_test)

94/94 [==============================] - 0s 4ms/step - loss: 0.4481 - mae: 0.4969 - mape: 0.3765

In [17]:
print("MSE: {:.2f}".format(test_loss))
print("MAE: {:.2f}".format(test_mae))
print("MAPE: {:.2%}".format(test_mape))

MSE: 0.45
MAE: 0.50
MAPE: 37.65%