In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("book.csv")

In [3]:
df

,ChildBks,YouthBks,CookBks,DoItYBks,RefBks,ArtBks,GeogBks,ItalCook,ItalAtlas,ItalArt,Florence
0,0,1,0,1,0,0,1,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0
3,1,1,1,0,1,0,1,0,0,0,0
4,0,0,1,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
1995,0,0,1,0,0,1,1,1,0,1,1
1996,0,0,0,0,0,0,0,0,0,0,0
1997,0,0,0,0,0,0,0,0,0,0,0
1998,0,0,1,0,0,0,0,0,0,0,0
1999,0,0,0,0,0,0,0,0,0,0,0

In [4]:
dist = pairwise_distances(df, metric='cosine')
dist

array([[0., 1., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 0., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [5]:
sim = 1 - pairwise_distances(df, metric='cosine')
sim

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [6]:
similarity =  pd.DataFrame(sim)
similarity

,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
0,1.000000,0.000000,0.0,0.516398,0.408248,0.000000,0.577350,0.408248,0.408248,0.577350,...,0.516398,0.000000,0.654654,0.0,0.0,0.235702,0.0,0.0,0.000000,0.0
1,0.000000,1.000000,0.0,0.447214,0.000000,0.577350,0.000000,0.000000,0.707107,0.500000,...,0.447214,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
2,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
3,0.516398,0.447214,0.0,1.000000,0.632456,0.258199,0.447214,0.632456,0.316228,0.894427,...,0.600000,0.000000,0.507093,0.0,0.0,0.365148,0.0,0.0,0.447214,0.0
4,0.408248,0.000000,0.0,0.632456,1.000000,0.000000,0.000000,0.000000,0.000000,0.707107,...,0.632456,0.000000,0.534522,0.0,0.0,0.577350,0.0,0.0,0.707107,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0.235702,0.000000,0.0,0.365148,0.577350,0.471405,0.000000,0.000000,0.000000,0.408248,...,0.547723,0.408248,0.771517,0.0,0.0,1.000000,0.0,0.0,0.408248,0.0
1996,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
1997,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
1998,0.000000,0.000000,0.0,0.447214,0.707107,0.000000,0.000000,0.000000,0.000000,0.500000,...,0.447214,0.000000,0.377964,0.0,0.0,0.408248,0.0,0.0,1.000000,0.0
1999,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0

In [7]:
np.fill_diagonal(similarity.values,0)

In [8]:
similarity

,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
0,0.000000,0.000000,0.0,0.516398,0.408248,0.000000,0.577350,0.408248,0.408248,0.577350,...,0.516398,0.000000,0.654654,0.0,0.0,0.235702,0.0,0.0,0.000000,0.0
1,0.000000,0.000000,0.0,0.447214,0.000000,0.577350,0.000000,0.000000,0.707107,0.500000,...,0.447214,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
2,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
3,0.516398,0.447214,0.0,0.000000,0.632456,0.258199,0.447214,0.632456,0.316228,0.894427,...,0.600000,0.000000,0.507093,0.0,0.0,0.365148,0.0,0.0,0.447214,0.0
4,0.408248,0.000000,0.0,0.632456,0.000000,0.000000,0.000000,0.000000,0.000000,0.707107,...,0.632456,0.000000,0.534522,0.0,0.0,0.577350,0.0,0.0,0.707107,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0.235702,0.000000,0.0,0.365148,0.577350,0.471405,0.000000,0.000000,0.000000,0.408248,...,0.547723,0.408248,0.771517,0.0,0.0,0.000000,0.0,0.0,0.408248,0.0
1996,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
1997,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
1998,0.000000,0.000000,0.0,0.447214,0.707107,0.000000,0.000000,0.000000,0.000000,0.500000,...,0.447214,0.000000,0.377964,0.0,0.0,0.408248,0.0,0.0,0.000000,0.0
1999,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0

In [9]:
similarity.idxmax()

0       231
1        21
2         0
3       158
4        11
       ...
1995     63
1996      0
1997      0
1998     16
1999      0
Length: 2000, dtype: int64