In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('forestfires.csv')
df

,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
0,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,...,0,0,0,0,1,0,0,0,0,small
1,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,...,0,0,0,0,0,0,0,1,0,small
2,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,...,0,0,0,0,0,0,0,1,0,small
3,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,...,0,0,0,0,1,0,0,0,0,small
4,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,...,0,0,0,0,1,0,0,0,0,small
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,aug,sun,81.6,56.7,665.6,1.9,27.8,32,2.7,0.0,...,0,0,0,0,0,0,0,0,0,large
513,aug,sun,81.6,56.7,665.6,1.9,21.9,71,5.8,0.0,...,0,0,0,0,0,0,0,0,0,large
514,aug,sun,81.6,56.7,665.6,1.9,21.2,70,6.7,0.0,...,0,0,0,0,0,0,0,0,0,large
515,aug,sat,94.4,146.0,614.7,11.3,25.6,42,4.0,0.0,...,0,0,0,0,0,0,0,0,0,small
516,nov,tue,79.5,3.0,106.7,1.1,11.8,31,4.5,0.0,...,0,0,0,0,0,0,1,0,0,small

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 31 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   month          517 non-null    object
 1   day            517 non-null    object
 2   FFMC           517 non-null    float64
 3   DMC            517 non-null    float64
 4   DC             517 non-null    float64
 5   ISI            517 non-null    float64
 6   temp           517 non-null    float64
 7   RH             517 non-null    int64
 8   wind           517 non-null    float64
 9   rain           517 non-null    float64
 10  area           517 non-null    float64
 11  dayfri         517 non-null    int64
 12  daymon         517 non-null    int64
 13  daysat         517 non-null    int64
 14  daysun         517 non-null    int64
 15  daythu         517 non-null    int64
 16  daytue         517 non-null    int64
 17  daywed         517 non-null    int64
 18  monthapr       517 non-null    int64
 19  monthaug       517 non-null    int64
 20  monthdec       517 non-null    int64
 21  monthfeb       517 non-null    int64
 22  monthjan       517 non-null    int64
 23  monthjul       517 non-null    int64
 24  monthjun       517 non-null    int64
 25  monthmar       517 non-null    int64
 26  monthmay       517 non-null    int64
 27  monthnov       517 non-null    int64
 28  monthoct       517 non-null    int64
 29  monthsep       517 non-null    int64
 30  size_category  517 non-null    object
dtypes: float64(8), int64(20), object(3)
memory usage: 125.3+ KB

In [4]:
le = LabelEncoder()
df['month'] = le.fit_transform(df['month'])
df['day'] = le.fit_transform(df['day'])
df['size_category'] = le.fit_transform(df['size_category'])

In [5]:
X = df.drop('size_category', axis=1)
y = df['size_category']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [6]:
X_train

,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,monthdec,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep
386,11,3,90.5,96.7,750.5,11.4,20.6,55,5.4,0.0,...,0,0,0,0,0,0,0,0,0,1
56,11,5,90.3,80.7,730.2,6.3,17.8,63,4.9,0.0,...,0,0,0,0,0,0,0,0,0,1
457,1,6,91.7,191.4,635.9,7.8,19.9,50,4.0,0.0,...,0,0,0,0,0,0,0,0,0,0
60,7,3,89.3,51.3,102.2,9.6,11.5,39,5.8,0.0,...,0,0,0,0,0,1,0,0,0,0
229,1,2,92.2,81.8,480.8,11.9,16.4,43,4.0,0.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,7,0,91.2,48.3,97.8,12.5,15.8,27,7.6,0.0,...,0,0,0,0,0,1,0,0,0,0
277,2,1,85.4,25.4,349.7,2.6,4.6,21,8.5,0.0,...,1,0,0,0,0,0,0,0,0,0
9,11,2,92.5,88.0,698.6,7.1,22.8,40,4.0,0.0,...,0,0,0,0,0,0,0,0,0,1
359,11,0,92.5,122.0,789.7,10.2,21.1,39,2.2,0.0,...,0,0,0,0,0,0,0,0,0,1
192,1,5,94.8,108.3,647.1,17.0,24.6,22,4.5,0.0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
X_test

,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,monthdec,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep
213,7,1,87.6,52.2,103.8,5.0,11.0,46,5.8,0.0,...,0,0,0,0,0,1,0,0,0,0
435,5,2,90.8,84.7,376.6,5.6,23.8,51,1.8,0.0,...,0,0,0,1,0,0,0,0,0,0
343,11,1,91.5,130.1,807.1,7.5,15.9,51,4.5,0.0,...,0,0,0,0,0,0,0,0,0,1
230,11,6,92.9,133.3,699.6,9.2,26.4,21,4.5,0.0,...,0,0,0,0,0,0,0,0,0,1
171,1,6,85.6,90.4,609.6,6.6,17.4,50,4.0,0.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,11,2,93.4,145.4,721.4,8.1,29.6,27,2.7,0.0,...,0,0,0,0,0,0,0,0,0,1
49,7,1,87.6,52.2,103.8,5.0,11.0,46,5.8,0.0,...,0,0,0,0,0,1,0,0,0,0
100,1,3,91.4,142.4,601.4,10.6,19.8,39,5.4,0.0,...,0,0,0,0,0,0,0,0,0,0
153,11,0,94.3,85.1,692.3,15.9,20.1,47,4.9,0.0,...,0,0,0,0,0,0,0,0,0,1
250,1,6,93.1,157.3,666.7,13.5,26.8,25,3.1,0.0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
y_train

386    0
56     1
457    0
60     1
229    0
      ..
70     1
277    0
9      1
359    0
192    0
Name: size_category, Length: 413, dtype: int32

In [9]:
y_test

213    0
435    1
343    1
230    0
171    1
      ..
154    1
49     1
100    1
153    1
250    1
Name: size_category, Length: 104, dtype: int32

In [10]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
X_train

array([[ 1.22376001,  0.13759402, -0.02655293, ..., -0.04926646,
        -0.17298898,  1.45903663],
       [ 1.22376001,  1.18993347, -0.06158922, ..., -0.04926646,
        -0.17298898,  1.45903663],
       [-1.07985386,  1.7161032 ,  0.18366482, ..., -0.04926646,
        -0.17298898, -0.68538375],
       ...,
       [ 1.22376001, -0.38857571,  0.32380998, ..., -0.04926646,
        -0.17298898,  1.45903663],
       [ 1.22376001, -1.44091516,  0.32380998, ..., -0.04926646,
        -0.17298898,  1.45903663],
       [-1.07985386,  1.18993347,  0.72672733, ..., -0.04926646,
        -0.17298898, -0.68538375]])

In [12]:
X_test

array([[ 0.30231446, -0.91474543, -0.53457915, ..., -0.04926646,
        -0.17298898, -0.68538375],
       [-0.15840831, -0.38857571,  0.02600151, ..., -0.04926646,
        -0.17298898, -0.68538375],
       [ 1.22376001, -0.91474543,  0.14862853, ..., -0.04926646,
        -0.17298898,  1.45903663],
       ...,
       [-1.07985386,  0.13759402,  0.13111038, ..., -0.04926646,
        -0.17298898, -0.68538375],
       [ 1.22376001, -1.44091516,  0.6391366 , ..., -0.04926646,
        -0.17298898,  1.45903663],
       [-1.07985386,  1.7161032 ,  0.42891885, ..., -0.04926646,
        -0.17298898, -0.68538375]])

In [13]:
svm = SVC(kernel='linear')
svm.fit(X_train, y_train)

SVC(kernel='linear')

In [14]:
y_pred = svm.predict(X_test)
score = svm.score(X_test, y_test)
print('Accuracy:', score)

Accuracy: 0.9230769230769231

In [15]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      0.77      0.85        30
           1       0.91      0.99      0.95        74

    accuracy                           0.92       104
   macro avg       0.94      0.88      0.90       104
weighted avg       0.93      0.92      0.92       104